---
# Create services
- name: Setup secor raw telemetry sync process
  vars:
    description: Secor raw telemetry sync service
    script_name: secor-raw
    script_dir: "{{ sbin_path }}"
    grep_key: "{{ secor.raw_home }}/secor-0.2-SNAPSHOT.jar"
    process: java
    service_home: "{{user_home}}/secor-raw"
    process_args: -Xms256M -Xmx512M -ea -Dsecor_group=raw -Dlog4j.configuration=log4j.{{ env }}.properties -Dconfig=secor.{{ env }}.partition.properties -cp secor-0.2-SNAPSHOT.jar:lib/* com.pinterest.secor.main.ConsumerMain
  template: src=servicify-process.j2 dest={{ script_dir }}/{{ script_name }} mode=755 owner=ec2-user group=ec2-user
  tags:
    - secor

- name: Setup secor derived telemetry sync process
  vars:
    description: Secor derived telemetry sync service
    script_name: secor-me
    script_dir: "{{ sbin_path }}"
    grep_key: "{{ secor.me_home }}/secor-0.2-SNAPSHOT.jar"
    process: java
    service_home: "{{user_home}}/secor-me"
    process_args: -Xms256M -Xmx512M -ea -Dsecor_group=me -Dlog4j.configuration=log4j.{{ env }}.properties -Dconfig=secor.{{ env }}.partition.properties -cp secor-0.2-SNAPSHOT.jar:lib/* com.pinterest.secor.main.ConsumerMain
  template: src=servicify-process.j2 dest={{ script_dir }}/{{ script_name }} mode=755 owner=ec2-user group=ec2-user
  tags:
    - secor
  
- name: Setup cassandra process as service
  vars:
    description: Cassandra service
    script_name: cassandra-service
    script_dir: "{{ sbin_path }}"
    grep_key: org.apache.cassandra.service.CassandraDaemon
    process: "bin/cassandra"
    service_home: "{{analytics.home}}/apache-cassandra-3.7"
    process_args: 
  template: src=servicify-process.j2 dest={{ sbin_path }}/{{ script_name }} mode=755 owner=ec2-user group=ec2-user
  tags:
    - analytics

- name: Setup analytics API as service
  vars:
    description: Analytics API service
    script_name: api-service
    script_dir: "{{ sbin_path }}"
    grep_key: play.core.server.ProdServerStart
    process: java
    service_home: "{{analytics.home}}/api/analytics-api-1.0"
    process_args: -cp 'lib/*' {{ api_args }} play.core.server.ProdServerStart {{ api_home }}
  template: src=servicify-process.j2 dest={{ sbin_path }}/{{ script_name }} mode=755 owner=ec2-user group=ec2-user
  tags:
    - api    