---
- hosts: dev
  become: yes
  become_method: sudo
  vars:
       bucket: sandbox-data-store 
       brokerlist: 172.31.1.92:9092 
       topic: sandbox.telemetry.derived 
  roles: 
        - copy
        - run-cql
        - scripts
        - cron-dev
  tags: 
       - dev
- hosts: qa
  become: yes
  become_method: sudo
  vars:
       bucket: qa-data-store 
       brokerlist: 172.31.1.92:9092 
       topic: qa.telemetry.derived 
  roles: 
        - copy
        - run-cql
        - scripts
        - cron-qa
  tags: 
       - qa
- hosts: prod
  become: yes
  become_method: sudo
  vars:
       bucket: prod-data-store 
       brokerlist: 10.10.1.207:9092 
       topic: production.telemetry.derived
      # cassandra-ip: 54.169.179.102
  roles: 
        - copy
        - run-cql
        - scripts 
        - cron-prod
  tags: 
       - prod
