---
- name: remove Spark 1.6.2 hadoop 2.3
  file: path={{ analytics.home }}/spark-1.6.2-bin-hadoop2.3 state=absent
  tags:
    - analytics

- name: Download Apache Spark 2.0.1 hadoop 2.7
  get_url: url=http://mirror.fibergrid.in/apache/spark/spark-2.0.1/spark-2.0.1-bin-hadoop2.7.tgz dest={{ analytics.home }}/spark-2.0.1-bin-hadoop2.7.tgz timeout=1000 force=no owner=ec2-user group=ec2-user
  tags:
    - analytics

- name: Unarchive Spark
  unarchive: src={{ analytics.home }}/spark-2.0.1-bin-hadoop2.7.tgz dest={{ analytics.home }}/ copy=no group=ec2-user owner=ec2-user creates={{ analytics.home }}/spark-2.0.1-bin-hadoop2.7
  tags:
    - analytics

- name: Remove Guava 14.0.1 from Spark jars folder
  file: path={{ analytics.home }}/spark-2.0.1-bin-hadoop2.7/jars/guava-14.0.1.jar state=absent
  tags:
    - analytics

- name: Download Guava 19.0 and copy to Spark jars folder
  get_url: url=http://central.maven.org/maven2/com/google/guava/guava/19.0/guava-19.0.jar dest={{ analytics.home }}/spark-2.0.1-bin-hadoop2.7/jars/guava-19.0.jar timeout=1000 force=no owner=ec2-user group=ec2-user
  tags:
    - analytics

- name: remove SPARK_HOME
  lineinfile: dest=.bash_profile line='SPARK_HOME=/home/ec2-user/spark-1.6.2-bin-hadoop2.3' state=absent 
  tags:
    - analytics

- name: remove Export SPARK_HOME
  lineinfile: dest=.bash_profile  line='export SPARK_HOME' state=absent
  tags:
    - analytics

- name: remove Add SPARK_HOME to the PATH
  lineinfile: dest=.bash_profile line='PATH=$PATH:$SPARK_HOME/bin' state=absent
  tags:
    - analytics

- name: Update bashrc for SPARK_HOME
  lineinfile: dest=.bash_profile line='SPARK_HOME=/mnt/data/analytics/spark-2.0.1-bin-hadoop2.7' state=present insertafter=EOF create=yes
  tags:
    - analytics

- name: Export SPARK_HOME
  lineinfile: dest=.bash_profile  line='export SPARK_HOME' state=present insertafter=EOF create=yes
  tags:
    - analytics

- name: Add SPARK_HOME to the PATH
  lineinfile: dest=.bash_profile line='PATH=$PATH:$SPARK_HOME/bin' state=present insertafter=EOF create=yes
  tags:
    - analytics


- name: export PATH
  lineinfile: dest=.bash_profile line='export PATH' state=present insertafter=EOF create=yes
  tags:
    - analytics

- name: Update spark default conf
  template: src=spark-defaults.j2 dest={{ spark.home }}/conf/spark-defaults.conf mode=755 owner=ec2-user group=ec2-user
  tags:
    - analytics    
