---
# tasks file for run-vidyavani
- name: copy the zip file
  copy: src=script.zip dest={{ analytics.home }}
  tags:
    - analytics

- name: extarct 
  unarchive: src={{ analytics.home }}/script.zip  dest={{ analytics.home }} copy=no group=ec2-user owner=ec2-user creates={{ analytics.home }}/script
  tags:
    - analytics

- name: copy to the paths
  become: yes 
  command: mv /mnt/data/analytics/script/{{ item }} /mnt/data/analytics/scripts
  with_items:
             - VidyavaniCnQ
             - GenieSearch
             - vidyavaani
  tags:
    - analytics

- name: remove script 
  file: path={{ analytics.home }}/{{ item }} state=absent
  with_items:
             - script 
             - script.zip
  tags:
    - analytics
