---
- name: Copy the config.zip properties artifact for secor-me
  copy: src=config.zip dest=/home/ec2-user/secor-me owner=ec2-user group=ec2-user
  tags:
    - secor-me


- name: Status of the secor-me service
  command: "/home/ec2-user/sbin/secor-me status"
  register: secor_status
  tags:
    - secor-me

- name: Stop the secor-me service
  command: "/home/ec2-user/sbin/secor-me stop"
  when: "secor_status.stdout.find('RUNNING') != -1"
  async: 10
  poll: 5
  tags:
    - secor-me


- name: Unarchive config.zip artifact
  command: "unzip -o config.zip"
  args:
       chdir: /home/ec2-user/secor-me
  tags:
    - secor-me

- name: delete config.zip
  file: path=/home/ec2-user/secor-me/config.zip state=absent
  tags:
    - secor-me

- name: Start the secor-me service
  command: "/home/ec2-user/sbin/secor-me start"
  async: 20
  poll: 5
  tags:
    - secor-me
#**********************Secor-raw

- name: Copy the config.zip properties artifact for secor-raw
  copy: src=config.zip dest=/home/ec2-user/secor-raw owner=ec2-user group=ec2-user
  tags:
    - secor-raw

- name: Status of the secor-raw service
  command: "/home/ec2-user/sbin/secor-raw status"
  register: secor_status
  tags:
    - secor-raw

- name: Stop the secor-raw service
  command: "/home/ec2-user/sbin/secor-raw stop"
  when: "secor_status.stdout.find('RUNNING') != -1"
  async: 10
  poll: 5
  tags:
    - secor-raw

- name: Unarchive config.zip artifact
  command: unzip -o config.zip
  args:
       chdir: /home/ec2-user/secor-raw
  tags:
    - secor-raw

- name: delete config.zip
  file: path=/home/ec2-user/secor-raw/config.zip state=absent
  tags:
    - secor-raw


- name: Start the secor-raw service
  command: "/home/ec2-user/sbin/secor-raw start"
  async: 20
  poll: 5
  tags:
    - secor-raw