---
# tasks file for cassandra

- name: Download cassandra
  become: yes
  become_user: ec2-user
  get_url: url=http://mirror.fibergrid.in/apache/cassandra/2.2.6/apache-cassandra-2.2.6-bin.tar.gz dest=/home/ec2-user/apache-cassandra-2.2.6-bin.tar.gz timeout=1000 force=no owner=ec2-user

- name: Unarchive cassandra
  become: yes
  become_user: ec2-user
  unarchive: src=/home/ec2-user/apache-cassandra-2.2.6-bin.tar.gz dest=/mnt/data/analytics/ copy=no group=ec2-user owner=ec2-user creates=/mnt/data/analytics/apache-cassandra-2.2.6

- name: Update bash_profile for CASSANDRA_HOME
  become: yes
  become_user: ec2-user
  lineinfile: dest=.bash_profile line='CASSANDRA_HOME=/mnt/data/analytics/apache-cassandra-2.2.6' state=present insertafter=EOF create=yes

- name: Export CASSANDRA_HOME
  become: yes
  become_user: ec2-user
  lineinfile: dest=.bash_profile  line='export CASSANDRA_HOME' state=present insertafter=EOF create=yes

- name: Add CASSANDRA_HOME to the PATH
  become: yes
  become_user: ec2-user
  lineinfile: dest=.bash_profile line='PATH=$PATH:$CASSANDRA_HOME/bin' state=present insertafter=EOF create=yes
 
- name: start cassandra
  become: yes
  become_user: ec2-user
  shell: nohup /mnt/data/analytics/apache-cassandra-2.2.6/bin/cassandra &
  async: 60
  poll: 60