---
# tasks file for copy

- name: copy the api artifact
  become: yes
  copy: src=analytics-api-1.0-dist.zip dest=/mnt/data/analytics/api owner=ec2-user group=ec2-user

- name: Unarchive api artifact
  become: yes
  become_user: ec2-user
  unarchive: src=/mnt/data/analytics/api/analytics-api-1.0-dist.zip dest=/mnt/data/analytics/api copy=no group=ec2-user owner=ec2-user mode=755

- stat: path=/mnt/data/analytics/api/analytics-api-1.0/RUNNING_PID
  become: yes
  become_user: ec2-user
  register: check_file

- name: Stop the api
  become: yes
  shell: kill `cat /mnt/data/analytics/api/analytics-api-1.0/RUNNING_PID`
  async: 20
  poll: 10
  when: check_file.stat.exists == true