---

- name: Copy Data Products
  copy: src=batch-models-1.0.jar dest={{ analytics_home }}/models
  tags:
    - anaytics

- name: Copy Framework Library
  copy: src=analytics-framework-1.0.jar dest={{ analytics_home }}/models
  tags:
    - anaytics

- name: Copy Scripts - Model Config
  template: src=model-config.j2 dest={{ analytics_home }}/scripts/model-config.sh mode=755 owner=ec2-user group=ec2-user
  tags:
    - anaytics

- name: Copy Scripts - Replay Job
  template: src=replay-job.j2 dest={{ analytics_home }}/scripts/replay-job.sh mode=755 owner=ec2-user group=ec2-user
  tags:
    - anaytics

- name: Copy Scripts - Replay Updater
  template: src=replay-updater.j2 dest={{ analytics_home }}/scripts/replay-updater.sh mode=755 owner=ec2-user group=ec2-user
  tags:
    - anaytics

- name: Copy Scripts - Replay Utils
  template: src=replay-utils.j2 dest={{ analytics_home }}/scripts/replay-utils.sh mode=755 owner=ec2-user group=ec2-user
  tags:
    - anaytics

- name: Copy Scripts - Run Job
  template: src=run-job.j2 dest={{ analytics_home }}/scripts/run-job.sh mode=755 owner=ec2-user group=ec2-user
  tags:
    - anaytics

- name: Create cron jobs
  cron: name={{ item.key }} minute={{ item.value.minute }} hour={{ item.value.hour }}  job="{{ analytics_home }}/scripts/run-job.sh {{ item.key }}"
  with_dict: "{{ jobs }}"
  tags:
    - anaytics