- name: Install Java8
  become: yes
  yum: name=java-1.8.0 state=latest
  ignore_errors: yes 
  register: result1
  tags:
    - always

- name: Remove Java7
  become: yes
  yum: name=java-1.7.0-openjdk state=absent
  tags:
    - always

- name: update /etc/environment
  become: yes
  lineinfile: dest=/etc/environment line='aws_key={{ lookup('env','lpa_aws_key') }}'  state=present insertafter=EOF create=yes
  tags:
    - always

- name: update /etc/environment
  become: yes
  lineinfile: dest=/etc/environment line='aws_secret={{ lookup('env','lpa_aws_secret') }}' state=present insertafter=EOF create=yes
  tags:
    - always

- name: Add aws keys to user profile
  lineinfile: dest=.bash_profile line='aws_key={{ lookup('env','lpa_aws_key') }}'  state=present insertafter=EOF create=yes
  tags:
    - always

- name: Add aws keys to user profile
  lineinfile: dest=.bash_profile line='aws_secret={{ lookup('env','lpa_aws_secret') }}'  state=present insertafter=EOF create=yes
  tags:
    - always  

- name: Create sbin directory to store services
  file: path={{ sbin_path }} owner=ec2-user group=ec2-user state=directory
  tags:
    - always

- name: Create directories for analytics
  become: yes
  file: path={{ item }} owner=ec2-user group=ec2-user state=directory
  with_items: "{{ analytics.paths }}"
  tags:
    - api
    - analytics

- name: Create secor directories
  become: yes
  file: path={{ item }} owner=ec2-user group=ec2-user state=directory
  with_items: "{{ secor.paths }}"
  tags:
    - secor