---
# tasks file for createpath
- name: Setup secor raw telemetry sync process
  become: yes
  vars:
    description: Secor raw telemetry sync service
    script_name: secor-raw
    script_dir: /home/ec2-user/sbin
    grep_key: secor-raw
    process: java
    process_args: -Xms256M -Xmx512M -ea -Dsecor_group=raw -Dlog4j.configuration=log4j.{{ env }}.properties -Dconfig=secor.{{ env }}.partition.properties -cp /home/ec2-user/secor-raw/secor-0.2-SNAPSHOT.jar:/home/ec2-user/secor-raw/lib/* com.pinterest.secor.main.ConsumerMain
  template: src=servicify-process.j2 dest={{ script_dir }}/secor-raw mode=755 owner=ec2-user group=ec2-user

- name: Setup secor derived telemetry sync process
  become: yes
  vars:
    description: Secor derived telemetry sync service
    script_name: secor-me
    script_dir: /home/ec2-user/sbin
    grep_key: secor-me
    process: java
    process_args: -Xms256M -Xmx512M -ea -Dsecor_group=me -Dlog4j.configuration=log4j.{{ env }}.properties -Dconfig=secor.{{ env }}.partition.properties -cp /home/ec2-user/secor-me/secor-0.2-SNAPSHOT.jar:/home/ec2-user/secor-me/lib/* com.pinterest.secor.main.ConsumerMain
  template: src=servicify-process.j2 dest={{ script_dir }}/secor-me mode=755 owner=ec2-user group=ec2-user  