---

- name: Stop the api service
  command: "{{ sbin_path }}/api-service stop"
  when: "cassandra_status.stdout.find('RUNNING') != -1"
  async: 10
  poll: 5
  tags:
    - api

- name: Unarchive api artifact
  unarchive: src=/mnt/data/analytics/api/analytics-api-1.0-dist.zip dest=/mnt/data/analytics/api copy=no group=ec2-user owner=ec2-user mode=755  
  tags:
    - api

- name: Start the api service
  command: "{{ sbin_path }}/api-service start"
  async: 20
  poll: 5
  tags:
    - api