---

- name: Copy API artifact
  copy: src=analytics-api-1.0-dist.zip dest={{ api_home }}
  tags:
    - api

- name: Status of the api service
  command: "{{ sbin_path }}/api-service status"
  register: api_status
  tags:
    - api

- name: Stop the api service
  command: "{{ sbin_path }}/api-service stop"
  when: "api_status.stdout.find('RUNNING') != -1"
  async: 10
  poll: 5
  tags:
    - api

- name: Unarchive api artifact
  unarchive: src={{ api_root }}/analytics-api-1.0-dist.zip dest={{ api_root }} copy=no group=ec2-user owner=ec2-user mode=755  
  tags:
    - api

- name: Start the api service
  command: "{{ sbin_path }}/api-service start"
  async: 20
  poll: 5
  tags:
    - api