---
# tasks file for Spark

- name: Download Apache Spark
  become: yes
  become_user: ec2-user
  get_url: url=http://mirror.fibergrid.in/apache/spark/spark-1.5.2/spark-1.5.2-bin-hadoop2.3.tgz dest=/home/ec2-user/spark-1.5.2-bin-hadoop2.3.tgz timeout=1000 force=no owner=ec2-user

- name: Unarchive Spark
  become: yes
  become_user: ec2-user
  unarchive: src=/home/ec2-user/spark-1.5.2-bin-hadoop2.3.tgz dest=/home/ec2-user/ copy=no group=ec2-user owner=ec2-user creates=/home/ec2-user/spark-1.5.2-bin-hadoop2.3

- name: Update bashrc for SPARK_HOME
  become: yes
  become_user: ec2-user
  lineinfile: dest=.bash_profile line='SPARK_HOME=$HOME/spark-1.5.2-bin-hadoop2.3' state=present insertafter=EOF create=yes

- name: Export SPARK_HOME
  become: yes
  become_user: ec2-user
  lineinfile: dest=.bash_profile  line='export SPARK_HOME' state=present insertafter=EOF create=yes

- name: Add SPARK_HOME to the PATH
  become: yes
  become_user: ec2-user
  lineinfile: dest=.bash_profile line='PATH=$PATH:$SPARK_HOME/bin' state=present insertafter=EOF create=yes