---
# tasks file for Spark

- name: Download Apache Spark 
  become: yes
  command: wget http://mirror.fibergrid.in/apache/spark/spark-1.5.2/spark-1.5.2-bin-hadoop2.3.tgz 

- name: Extract Spark
  become: yes
  command: tar zxvf spark-1.5.2-bin-hadoop2.3.tgz 

- name: Update bashrc for SPARK_HOME
  become: yes
  become_user: ec2-user
  lineinfile: dest=$HOME/.bash_profile line='SPARK_HOME=$HOME/spark-1.5.2-bin-hadoop2.3' state=present insertafter=EOF create=yes

- name: Export SPARK_HOME
  become: yes
  become_user: ec2-user
  lineinfile: dest=$HOME/.bash_profile  line='export SPARK_HOME' state=present insertafter=EOF create=yes

- name: Add SPARK_HOME to the PATH
  become: yes
  become_user: ec2-user
  lineinfile: dest=$HOME/.bash_profile line='PATH=$PATH:$SPARK_HOME/bin' state=present insertafter=EOF create=yes
