---
# tasks file for cassandra

- name: Download cassandra
  get_url: url=http://archive.apache.org/dist/cassandra/3.7/apache-cassandra-3.7-bin.tar.gz dest={{ user_home }}/apache-cassandra-3.7-bin.tar.gz timeout=1000 force=no owner=ec2-user
  tags:
    - analytics
    - cassandra

- name: Unarchive cassandra
  unarchive: src={{ user_home }}/apache-cassandra-3.7-bin.tar.gz dest={{ analytics.home }}/ copy=no group=ec2-user owner=ec2-user creates={{ analytics.home }}/apache-cassandra-3.7
  tags:
    - analytics
    - cassandra

- name: Update bash_profile for CASSANDRA_HOME
  lineinfile: dest=.bash_profile line='CASSANDRA_HOME={{ analytics.home }}/apache-cassandra-3.7' state=present insertafter=EOF create=yes
  tags:
    - analytics
    - cassandra

- name: Export CASSANDRA_HOME
  lineinfile: dest=.bash_profile  line='export CASSANDRA_HOME' state=present insertafter=EOF create=yes
  tags:
    - analytics
    - cassandra

- name: Add CASSANDRA_HOME to the PATH
  lineinfile: dest=.bash_profile line='PATH=$PATH:$CASSANDRA_HOME/bin' state=present insertafter=EOF create=yes
  tags:
    - analytics
    - cassandra

- name: copy template cassandra.yml
  template: src=cassandra.j2 dest={{ analytics.home }}/apache-cassandra-3.7/conf/cassandra.yaml owner=ec2-user group=ec2-user mode=0751
  

- name: copy template host
  become: yes
  template: src=hosts.j2 dest=/etc/hosts 
  

- name: Status of the cassandra service
  command: "{{ sbin_path }}/cassandra-service status"
  register: cassandra_status
  tags:
    - analytics
    - cassandra

- name: Start the cassandra service
  command: "{{ sbin_path }}/cassandra-service start"
  when: "cassandra_status.stdout.find('RUNNING') == -1"
  async: 20
  poll: 5
  tags:
    - analytics
    - cassandra