---
# tasks file for start
- name: Extract the file
  become: yes
  command: tar -zxvf /mnt/secor/deploy/secor-{{ secor.version }}-SNAPSHOT-bin.tar.gz -C /mnt/secor-raw

- name: Start the process
  become: yes 
  comand: chdir=/mnt/secor-raw nohup java -Xms256M -Xmx512M -ea -Dsecor_group=raw -Dlog4j.configuration=log4j.{{ env }}.properties -Dconfig=secor.{{ env }}.partition.properties -cp secor-raw/secor-0.2-SNAPSHOT.jar:lib/* com.pinterest.secor.main.ConsumerMain &
