---
# tasks file for start
- name: Stop the Secor service
  become: yes
  become_user: ec2-user
  command: /home/ec2-user/sbin/secor-raw stop
  async: 10
  poll: 5

- name: Unarchive secor artifact
  become: yes
  become_user: ec2-user
  unarchive: src=/mnt/secor/secor-0.2-SNAPSHOT-bin.tar.gz dest=/home/ec2-user/secor-raw copy=no group=ec2-user owner=ec2-user

- name: Start the Secor service
  become: yes
  become_user: ec2-user
  command: /home/ec2-user/sbin/secor-raw start
  async: 20
  poll: 5