---
# tasks file for aws-setup
- name: Create Directory
  become: yes
  file: path=/mnt/data/analytics/api state=directory  

- name: Set permissions
  become: yes
  file: path=/mnt/data/analytics owner=ec2-user group=ec2-user recurse=yes