---
# tasks file for aws-setup
- name: Create Directory
  become: yes
  file: path=/mnt/data/analytics/api state=directory  

- name: Set permissions
  become: yes
  file: path=/mnt owner=ec2-user group=ec2-user mode=777 recurse=yes


