---
# tasks file for java

- name: Install add-apt-repostory
  sudo: yes
  apt: name=software-properties-common state=latest


- name: Add Oracle Java Repository
  sudo: yes
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept Java 8 License
  sudo: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Oracle Java 8
  sudo: yes
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default

- name: Update bashrc for JAVA_HOME
  become: yes
  lineinfile: dest={{ ansible_env.HOME }}/.bash_profile line='JAVA_HOME=/usr/lib/jvm/java-8-oracle' owner=ubuntu state=present insertafter=EOF create=True


- name: Export JAVA_HOME
  become: yes
  lineinfile: dest={{ ansible_env.HOME }}/.bash_profile  line='export JAVA_HOME' owner=ubuntu state=present insertafter=EOF create=True

- name: Add JAVA_HOME to the PATH
  become: yes  
  lineinfile: dest={{ ansible_env.HOME }}/.bash_profile line='PATH=$PATH:$JAVA_HOME/bin' owner=ubuntu state=present insertafter=EOF create=True

- name: ADD oracle-java8-set-default
  become: yes
  apt: name=oracle-java8-set-default state=present

