---
# tasks file for neo4j-python
- name: install neo4j
  get_url: url=http://dist.neo4j.org/neo4j-community-2.3.3-unix.tar.gz dest=/mnt/data/analytics/neo4j-community-2.3.3-unix.tar.gz timeout=1000 force=no owner=ec2-user 

- name: Unarchive neo4j
  unarchive: src=/mnt/data/analytics/neo4j-community-2.3.3-unix.tar.gz dest=/mnt/data/analytics copy=no group=ec2-user owner=ec2-user creates=/mnt/data/analytics/neo4j-community-2.3.3

- name: Check if neo4j is running
  shell: ps -ef | grep neo4j | grep -v grep | wc -l
  register: neo4j_process
  changed_when: false
  ignore_errors: true 

- name: Run neo4j
  command: chdir=/mnt/data/analytics/neo4j-community-2.3.3/bin ./neo4j start
  when: "neo4j_process.stdout == '0'"

- name: install julia
  get_url: url=https://julialang.s3.amazonaws.com/bin/linux/x64/0.4/julia-0.4.5-linux-x86_64.tar.gz dest=/mnt/data/analytics/julia-0.4.5-linux-x86_64.tar.gz timeout=1000 force=no owner=ec2-user

- name: Unarchive julia
  unarchive: src=/mnt/data/analytics/julia-0.4.5-linux-x86_64.tar.gz dest=/mnt/data/analytics copy=no group=ec2-user owner=ec2-user creates=/mnt/data/analytics/julia-2ac304dfba

- name: install gcc
  become: yes
  yum: name=gcc state=present

#- name: install python
#  become: yes
#  get_url: url=https://www.python.org/ftp/python/2.7.12/Python-2.7.12.tgz dest=/mnt/data/analytics/Python-2.7.12.tgz timeout=1000 force=no 

#- name: Unarchive python
#  become: yes
#  unarchive: src=/mnt/data/analytics/Python-2.7.12.tgz dest=/mnt/data/analytics copy=no  creates=/mnt/data/analytics/Python-2.7.12

#- name: move directory
#  become: yes
#  shell: chdir=/mnt/data/analytics/Python-2.7.12 ./configure


#- name: move directory
#  become: yes
#  shell: chdir=/mnt/data/analytics/Python-2.7.12 make 

#- name: move directory
#  become: yes
#  shell: chdir=/mnt/data/analytics/Python-2.7.12 make install    

- name: install modules
  pip: name={{ item }}
  with_items: 
            - nltk
            - py2neo
            - requests
            - numpy
            - langdetect
            - simplejson
            - mutagen
            - pydub
            - signalslot
            - SpeechRecognition
            - jsonschema
            - scipy
            - pandas
            - matplotlib


#- name: install pip modules
#  easy_install: name={{ item }} state=latest
#  with_items
