---
# tasks file for copy


- name: Copy the secor artifact
  copy: src=secor-me-1.0-bin.tar.gz dest={{ secor.artifact_dir }} owner=ec2-user group=ec2-user
  tags:
    - secor-me

- name: Status of the secor-me service
  command: "{{ sbin_path }}/secor-me status"
  register: secor_status
  tags:
    - secor-me

- name: Stop the secor-me service
  command: "{{ sbin_path }}/secor-me stop"
  when: "secor_status.stdout.find('RUNNING') != -1"
  async: 10
  poll: 5
  tags:
    - secor-me

- name: Unarchive secor-me artifact
  unarchive: src={{ secor.artifact_dir }}/secor-me-1.0-bin.tar.gz dest={{ secor.me_home }} copy=no group=ec2-user owner=ec2-user
  tags:
    - secor-me

- name: Start the secor-me service
  command: "{{ sbin_path }}/secor-me start"
  async: 20
  poll: 5
  tags:
    - secor-me

- name: Copy the secor artifact
  copy: src=secor-raw-1.0-bin.tar.gz dest={{ secor.artifact_dir }} owner=ec2-user group=ec2-user
  tags:
    - secor-raw

- name: Status of the secor-raw service
  command: "{{ sbin_path }}/secor-raw status"
  register: secor_status
  tags:
    - secor-raw

- name: Stop the secor-raw service
  command: "{{ sbin_path }}/secor-raw stop"
  when: "secor_status.stdout.find('RUNNING') != -1"
  async: 10
  poll: 5
  tags:
    - secor-raw

- name: Unarchive secor-raw artifact
  unarchive: src={{ secor.artifact_dir }}/secor-raw-1.0-bin.tar.gz dest={{ secor.raw_home }} copy=no group=ec2-user owner=ec2-user
  tags:
    - secor-raw

- name: Start the secor-raw service
  command: "{{ sbin_path }}/secor-raw start"
  async: 20
  poll: 5
  tags:
    - secor-raw

- name: Copy Scripts
  template: src=monitor-secor.j2 dest={{ user_home }}/monitor-secor.sh mode=755 owner=ec2-user group=ec2-user
  tags:
    - secor-raw
    - secor-me

- name: Create cron jobs
  cron: name={{ item.key }} minute={{ item.value.minute }} hour={{ item.value.hour }}  job="{{ user_home }}/monitor-secor.sh ./secor-raw/logs/secor-raw.log raw"
  with_dict: "{{ secor-raw-job }}"
  tags:
    - secor-raw

- name: Create cron jobs
  cron: name={{ item.key }} minute={{ item.value.minute }} hour={{ item.value.hour }}  job="{{ user_home }}/monitor-secor.sh ./secor-me/logs/secor-me.log me"
  with_dict: "{{ secor-me-job }}"
  tags:
    - secor-me